// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeCanvas.Core.Data;

#nullable disable

namespace TimeCanvas.Core.Migrations
{
    [DbContext(typeof(TimeCanvasDbContext))]
    partial class TimeCanvasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TimeCanvas.Core.Models.DayTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weekday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Weekday")
                        .IsUnique();

                    b.ToTable("DayTemplates");
                });

            modelBuilder.Entity("TimeCanvas.Core.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualMinutesUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TimeCanvas.Core.Models.TemplateTaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlannedDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DayTemplateId");

                    b.ToTable("TemplateTasks");
                });

            modelBuilder.Entity("TimeCanvas.Core.Models.TemplateTaskItem", b =>
                {
                    b.HasOne("TimeCanvas.Core.Models.DayTemplate", "DayTemplate")
                        .WithMany("Tasks")
                        .HasForeignKey("DayTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayTemplate");
                });

            modelBuilder.Entity("TimeCanvas.Core.Models.DayTemplate", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
