// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TimeCanvas.Core.Data.CompiledModels
{
    public partial class TimeCanvasDbContextModel
    {
        private TimeCanvasDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("4ba68ce3-f6d9-4e83-99f1-d4c63ac3221d"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var dayTemplate = DayTemplateEntityType.Create(this);
            var taskItem = TaskItemEntityType.Create(this);
            var templateTaskItem = TemplateTaskItemEntityType.Create(this);

            TemplateTaskItemEntityType.CreateForeignKey1(templateTaskItem, dayTemplate);

            DayTemplateEntityType.CreateAnnotations(dayTemplate);
            TaskItemEntityType.CreateAnnotations(taskItem);
            TemplateTaskItemEntityType.CreateAnnotations(templateTaskItem);

            AddAnnotation("ProductVersion", "10.0.11");
        }
    }
}
