// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TimeCanvas.Core.Data;
using TimeCanvas.Core.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TimeCanvasDbContext), typeof(TimeCanvasDbContextModel))]
